### ISSUE TITLE
feature request: hamt-filter, hamt-has-value? and hamt-map

### ISSUE THREAD

**Issue by dented42** [97jaz/hamt#3]
It would be helpful to have a `hamt-filter` function, in addition to an `hamt-has-value?` that just searches through all the values. However my main suggestion is `hamt-map`. Currently it returns a list, but it would be really nice to have a version that returns another hamt as well, especially if it can be written so that the resulting hamt shares as much structure as possible with the original.

I'd suggest making a`hamt-map/list` that aliases to hamt-map, and an `hamt-map/hamt` who's function takes a key and value, and returns a new key and value using `values`.

**Comment by 97jaz** [comment]
- `hamt-has-value?`: Sure, no problem.
- `hamt-filter`: Based on your `hamt-map` comments, I don't know if you're looking for a function that returns a list (which would follow the Racket idiom) or one that returns a hamt.

I think maybe instead of defining `hamt-filter` and `hamt-map/hamt`, it might be better to provide `for/hamt`. Then, if you want a list-returning `hamt-filter`, you could use:
```racket
;; assume h is a hamt
(for/list ([(k v) (in-dict h)]
           #:when (pred? k))
  v)
```

Or if you want a hamt-returning version, you could write:
```racket
(for/hamt ([(k v) (in-dict h)]
           #:when (pred? k))
  (values k v))
```

**Comment by 97jaz** [comment]
Or, to address the whole result type-issue more thoroughly, it would make sense for hamts to be generic collections, using [http://pkg-build.racket-lang.org/doc/alexis-collections/index.html].

**Comment by dented42** [comment]
I meant for it to return a hamt, not a list. But yeah, implementing the generic interface wwould probably be best. Thanks :)

**Comment by 97jaz** [comment]
So, I realize it's been ages. Ever since the built-in `hash` type was re-implemented as a HAMT (in C), this package has only been interesting as a curiosity, I think. At any rate, I implemented `hamt-has-value?` some time ago, but I realized that I never mentioned it here. And just now, I implemented `for/hamt` (and variants) and also implemented the `gen:collection`, `gen:countable`. and `gen:sequence` interfaces from the collections package.

I don't plan to do any new development on this package in the future, but I'll fix bugs.
