### ISSUE TITLE
Inefficient vector allocation?

### ISSUE THREAD

**Issue by Metaxal** [97jaz/hamt#4]
Hi,

I was just reading the code for inspiration, and saw this:
https://github.com/97jaz/hamt/blob/561cb6a447e9766dcb8abf2c01b30b87d91135f5/data/hamt/array.rkt#L37
This is probably not efficient as allocation and copy happen on each insertion, which means that after n insertions, the number of computation steps grows as O(n²), unless I'm missing something.

A simple remedy is to use [growable vectors](https://docs.racket-lang.org/data/gvector.html?q=growable) which increase and decrease the vector size by a constant factor each time, which keeps the O(n) order.

Though I'm not requesting anything, I just thought that you might be interested :)

Cheers,
Laurent

**Comment by 97jaz** [comment]
A few things:
1. This code is all obsolesced by the implementations of immutable hashes that have been in the main Racket distribution for years now. Anyone using this package would be better off just using the built-in immutable hashes.
2. Unless there's a bug here (which is, of course, possible), this shouldn't be O(n^2). A HAMT is a tree of small vectors. The maximum vector size is determined by the number of bits of the hash code that are examined at each level of the tree. In this implementation, 4 bits are used, so each vector has a maximum size of 2^4 = 16. The number of vector copies per insert is bounded by the height of the tree, since this data structure uses the common path-copying strategy shared by pretty much all immutable tree data structures. Since we have a branch factor of 16, the number of vector copies per insert will be log-base-16(n). 
3. Using growable vectors doesn't help, since these HAMTs are immutable. The growable vectors that you cited achieve their performance through mutability. On the other hand, we could use an immutable (tree-based) vector representation that has better asymptotic performance for updates, but asymptotic performance doesn't matter in this application, since the maximum vector size is so small.

**Comment by Metaxal** [comment]
Thanks for taking the time to reply. Yes, if the vectors are small enough, it doesn't matter anyway.
